package:
  name: dials
  version: "2.0.0a1"

source:
  - git_url: https://github.com/ndevenish/super-dials
    folder: modules
  - git_url: https://github.com/ndevenish/tbxcmake
    folder: modules/cmake
  - git_url: https://github.com/ndevenish/tbxtools
    folder: tbxtools

requirements:
#   build:
#     - python
#     - setuptools

  run:
    - pthread-stubs
    - py2app
    - python.app

    - "cctbx::hdf5_plugins"
    - "cctbx::libcxx"

    - "conda-forge::dials-data"
    - "conda-forge::mrcfile"
    - "conda-forge::msgpack-python=0.6.2"
    - "conda-forge::orderedset"
    - "conda-forge::procrunner>=1.0.2"
    - "conda-forge::pyrtf"

    - alabaster
    - biopython=1.73
    - bzip2
    - cython>=0.29,<0.30
    - docutils
    - future
    - h5py
    - hdf5
    - jinja2
    - jpeg
    - matplotlib-base>=3.0.2,<3.1
    - mock
    - nomkl
    - numpy>=1.15,<1.16
    - pillow>=5.4.1
    - pip
    - psutil
    - pytest>=4.5,<5.0
    - pytest-forked
    - pytest-mock
    - pytest-xdist
    - python>=3.6,<3.7
    - requests
    - scikit-learn=0.20.2
    - scipy=1.2.1
    - send2trash
    - setuptools
    - six
    - sphinx<1.9
    - sqlite
    - tabulate
    - tqdm=4.23.4
    - urllib3
    - wxpython>=4.0.1
    - xz
#     - python

# test:
#   imports:
#     -

# about:
#   home:
