package:
  name: dials
  version: "2.0.0a1"

build:
  number: 1

source:
  - git_url: https://github.com/ndevenish/super-dials
    folder: modules
    patches:
      - patches/0001-boost-graph-patch.patch
      - patches/0002-Replace-libtbx-env.patch
  - git_url: https://github.com/ndevenish/tbxcmake
    folder: modules/cmake
  - git_url: https://github.com/ndevenish/tbxtools
    folder: tbxtools

requirements:
  build:
    - python
    - git
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    # tbxtools
    - networkx
    - pyyaml
    - six
    - docopt
  host:
    - numpy
    - python
    #- docopt
    - six
    # Binary duplicates
    - boost<1.73
    - eigen
    - msgpack-c
    - hdf5
    - mesalib # [linux]
    - libglu  # [linux]
    - libtiff # [linux]


  run:
    # Extra things from this distribution
    - entrypoints

    # Things installed by bootstrap
    - boost<1.73
    - eigen
    - msgpack-c

    - pthread-stubs
    - py2app        # [mac]
    - python.app    # [mac]

    #- mesalib # [linux]
    #- libglu  # [linux]
    #- "cctbx::hdf5_plugins"
    #- "cctbx::libcxx"

    - "conda-forge::dials-data"
    - "conda-forge::mrcfile"
    - "conda-forge::msgpack-python"
    - "conda-forge::orderedset"
    - "conda-forge::procrunner>=1.0.2"
    - "conda-forge::pyrtf"

    - alabaster
    - biopython
    - bzip2
    - cython
    - docutils
    - future
    - h5py
    - hdf5
    - jinja2
    - jpeg
    - matplotlib-base
    - mock
    - nomkl
    - numpy
    - pillow>=5.4.1
    - pip
    - psutil
    - pytest>=4.5
    - pytest-forked
    - pytest-mock
    - pytest-xdist
    - python>=3.6
    - requests
    - scikit-learn
    - scipy
    - send2trash
    - setuptools
    - six
    - sphinx
    - sqlite
    - tabulate
    - tqdm
    - urllib3
    - wxpython>=4.0.1
    - xz
#     - python

# test:
#   imports:
#     -

# about:
#   home:
about:
    home: https://github.com/dials/dials
    license: BSD
    license_file: LICENSE
    summary: Diffraction Integration for Advanced Light Sources
